name: Docker Image Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Build the tagged image
      run: docker build . --file Dockerfile --tag nut-exporter:${{ github.sha }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag the Docker image
      run: |
        docker tag nut-exporter:${{ github.sha }} ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker tag nut-exporter:${{ github.sha }} ghcr.io/${{ github.repository }}:latest

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}:latest
